NCAR/wrfcloud

python/coverage.sh
python/src/wrfcloud/api/actions/__init__.py
python/src/wrfcloud/api/actions/roles.yaml
python/src/wrfcloud/api/actions/users.py
python/src/wrfcloud/api/audit/audit_dao.py
python/src/wrfcloud/dynamodb/dynamodb.py
python/src/wrfcloud/user/__init__.py
python/src/wrfcloud/user/basic.py
python/src/wrfcloud/user/user.py
python/src/wrfcloud/user/user_dao.py
python/test/resources/sample_users.yaml
python/test/wrfcloud/helper.py
python/test/wrfcloud/test_api_actions.py
python/test/wrfcloud/test_api_audit.py
python/test/wrfcloud/test_api_handler.py
python/test/wrfcloud/test_user.py

Closes #9
Is is another large PR.  Since we have github issues setup with templates now, I will make smaller issues so that they are easier to review.
No.  Additional API actions.
New unit tests can be run with python/coverage.sh.  90% of code is tested.
Setting up the test environment is non-trivial since it requires a local copy of DynamoDB.  RAL IT let me know last week that the AWS account should be set up tomorrow (Tuesday).  Then we can setup automated testing.
Documentation was not updated for this feature.
Yes.  90% of code is covered in the tests.
Yes, new tests have been added.

Feature 9/user mgmt actions

---

python/src/wrfcloud/api/actions/__init__.py
python/src/wrfcloud/api/actions/action.py
python/src/wrfcloud/api/actions/login.py
python/src/wrfcloud/api/actions/roles.yaml
python/src/wrfcloud/api/auth/__init__.py
python/src/wrfcloud/api/auth/refresh.py
python/src/wrfcloud/api/auth/table.yaml
python/src/wrfcloud/resources/env_vars.yaml
python/test/wrfcloud/helper.py
python/test/wrfcloud/test_api_actions.py
python/test/wrfcloud/test_api_handler.py
python/test/wrfcloud/test_user.py

New action to accept a refresh token and issue a new JWT and refresh token.
Added tests with coverage at 90%.
Updated to latest PyJWT and made minor changes.

New data management classes for RefreshTokens.

---

python/src/wrfcloud/runtime/__init__.py
python/src/wrfcloud/runtime/metgrid.py
python/src/wrfcloud/runtime/ungrib.py

These changes add new output.
Tested on Cheyenne using Mike's wrfcloud conda environment available on disk. run.py was run and output in test/ungrib and test/metgrid confirmed looked reasonable using ncview.
Reviewers can test on Cheyenne and should place files and source code in appropriate places, e.g. link WPSV4 and WRFV4 to wrfcloud/python/src/wrfcloud/runtime/ and place geo_em.d01.nc file in wrfcloud/python/src/wrfcloud/runtime/domains/test.
On Cheyenne:
`ln -sf /glade/p/ral/jntp/CCproject/wrfcloud/WRFV4.4_intel_dmpar/ WRFV4`
`ln -sf /glade/p/ral/jntp/CCproject/wrfcloud/WPSV4.4_intel_serial_large-file/ WPSV4`
`cp /glade/p/ral/jntp/CCproject/wrfcloud/wpsprd/geo_em.d01.nc $PATH_TO_CLONED_REPO/wrfcloud/python/src/wrfcloud/runtime/domains/test`
To test on an AWS cluster, need to address …

feature 22/nwp_scripts

---

python/src/wrfcloud/api/actions/__init__.py
python/src/wrfcloud/api/actions/password.py
python/src/wrfcloud/api/actions/roles.yaml
python/src/wrfcloud/api/actions/users.py
python/src/wrfcloud/api/audit/audit_dao.py
python/src/wrfcloud/api/audit/entry.py
python/src/wrfcloud/api/auth/__init__.py
python/src/wrfcloud/api/auth/refresh.py
python/src/wrfcloud/resources/email_templates/password_reset.html
python/src/wrfcloud/resources/env_vars.yaml
python/src/wrfcloud/user/user.py
python/test/wrfcloud/test_api_actions.py
python/test/wrfcloud/test_user.py
web/src/app/app-routing.module.ts
web/src/app/app.module.ts
web/src/app/login/login.component.html
web/src/app/login/login.component.sass
web/src/app/login/login.component.ts
web/src/app/reset-password/reset-password.component.html
web/src/app/reset-password/reset-password.component.sass
web/src/app/reset-password/reset-password.component.spec.ts
web/src/app/reset-password/reset-password.component.ts
web/src/app/wrfcloud-api.ts
web/src/globals.sass

API changes:
- Added the RequestPasswordRecoveryToken API action.
- Granted permission to anonymous users to run the RequestPasswordRecoveryToken action.
- Updated the email template to reset a password.
- Added step when validating reset token to check the expiration time.
UI changes:
- Added section to Login page to show recovery instructions after a token request has been successfully submitted.
- Added button and code to submit recovery request to API
- Added ResetPassword component to allow user to reset password with the link from the email.
Tests:
- Fixed a few tests
- Added new tests to cover new API code
No
Ran pylint on the API, ran test suite on the python package, wrote new tests for new Python code and checked coverage, tested UI to reset passwords.
@michelleharrold and …

Feature 29/password recovery

---

python/src/setup.py
python/src/wrfcloud/resources/env_vars.yaml
python/src/wrfcloud/runtime/__init__.py
python/src/wrfcloud/runtime/run.py
python/src/wrfcloud/runtime/tools/__init__.py
python/src/wrfcloud/runtime/tools/get_grib_input.py
python/src/wrfcloud/runtime/ungrib.py

On Cheyenne, I ran the run.py script for several initialization start times using the Caribbean-based namelist. Tests included changing the initialization time to test functionality to pull from NOMADS or S3 based on data availability. I also modified the input_freq_sec to test different input frequencies as well as testing 00 and 12 UTC initializations.
To pull data from NOMADS or S3, I modified the yml file to have an empty string for local_data.
Note 1: I did have to add several Python packages to the wrfcloud conda environment (e.g., boto3).
Note 2: Additional warning and error checking will need to be implemented.
@hahnd - Can you please do a review of the code changes to offer any Python-related suggestions as needed?
@fossell - Can you please run a …

Feature 28/pull gfs data

---

python/src/wrfcloud/aws/pcluster.py
python/src/wrfcloud/aws/resources/cf_imagebuilder_wrf_intel.yaml

This is a new software, no output yet.
1. Building UPP was done manually by logging into the headnode of a cluster. Environment and procedures were refined and tested and then translated to the wrfcloud/aws/resources/cf_imagebuilder_wrf_intel.yaml.
2.  The wrfcloud package with the updated cf_imagebuilder_wrf_intel.yaml was rebuilt. I then attempted to follow directions from @hahnd to rebuild the AMI:
`wrfcloud-imagebuilder replace` - successful
`wrfcloud-imagebuilder build`- Unclear what happened?
After running the wrfcloud-imagebuilder build command, I can see teh Build Instance running on the EC2 web console, but nothing else seemed to happen. No new AMI's were showing up in the AMI web console, only the original one created by David a couple months ago.  I couldn't login to the …

Feature 50/ Install UPP

---

python/src/wrfcloud/jobs/__init__.py
python/src/wrfcloud/jobs/job.py
python/src/wrfcloud/jobs/job_dao.py
python/src/wrfcloud/jobs/table.yaml
python/src/wrfcloud/resources/env_vars.yaml
python/src/wrfcloud/setup/aws/cf_wrfcloud_data.yaml
python/test/resources/sample_jobs.yaml
python/test/wrfcloud/helper.py
python/test/wrfcloud/test_jobs.py

New unit tests have been added for this code and there is 100% code coverage.
Run pylint to look for errors and significant warnings.

WRF Job data model and CRUD operations.

---

python/src/setup.py
python/src/wrfcloud/log.py
python/src/wrfcloud/resources/env_vars.yaml
python/src/wrfcloud/runtime/__init__.py
python/src/wrfcloud/runtime/metgrid.py
python/src/wrfcloud/runtime/postproc.py
python/src/wrfcloud/runtime/real.py
python/src/wrfcloud/runtime/run.py
python/src/wrfcloud/runtime/tools/__init__.py
python/src/wrfcloud/runtime/tools/get_grib_input.py
python/src/wrfcloud/runtime/tools/make_wps_namelist.py
python/src/wrfcloud/runtime/ungrib.py
python/src/wrfcloud/runtime/wrf.py
python/src/wrfcloud/system.py

I changed the logging over and switched the model processes to classes.  I am not sure how to test this code, but I think you both know better than I do.  Please let me know if anything is unclear -- I want to make sure everyone is comfortable with these changes.

First attempt and logging and OOP changes.

---

python/src/wrfcloud/runtime/ungrib.py

Added sorting to make sure the downloaded GRIB files from NOMADS or S3 are first sorted alphabetically before linked to the GRIBFILE.AA* series for ungrib. This was previously only done for local data sources, this PR adds sorting for NOMADS and S3 data sources as well.
This PR will fix #65.
The grib files linked to the GRIBFILE.AA* series will change and now be in correct order, as described in the issue. 
This change was tested on Cheyenne by setting local_data to an empty string, e.g. `local_data: ''` in the run.yml file and then running run.py.
Check out the feature branch, change run.yml to have` local_data: ''` and then run run.py. Ensure that the GRIBFILE.AA* list in output/ungrib directory is linked to chronologically increasing forecast hours of …

feature-65/fix_grib_file_sort

---

python/src/wrfcloud/api/actions/__init__.py
python/src/wrfcloud/api/actions/action.py
python/src/wrfcloud/api/actions/jobs.py
python/src/wrfcloud/api/actions/roles.yaml
python/src/wrfcloud/api/actions/wrf.py
python/src/wrfcloud/api/handler.py
python/src/wrfcloud/jobs/__init__.py
python/src/wrfcloud/jobs/job_dao.py
python/src/wrfcloud/resources/env_vars.yaml
python/src/wrfcloud/setup/aws/cf_wrfcloud_certificate.yaml
python/src/wrfcloud/setup/aws/cf_wrfcloud_data.yaml
python/src/wrfcloud/setup/aws/cf_wrfcloud_webapp.yaml
python/src/wrfcloud/subscribers/__init__.py
python/src/wrfcloud/subscribers/subscriber.py
python/src/wrfcloud/subscribers/subscriber_dao.py
python/src/wrfcloud/subscribers/table.yaml
python/src/wrfcloud/subscribers/websocket_tools.py
python/test/resources/sample_subscribers.yaml
python/test/wrfcloud/helper.py
python/test/wrfcloud/test_subscribers.py
web/src/app/app.component.ts
web/src/app/app.module.ts
web/src/app/client-api.ts
web/src/app/view-jobs/view-jobs.component.html
web/src/app/view-jobs/view-jobs.component.ts

Closes #61 
To test:
1. Login to the web application and navigate to the _WRF Jobs_ tab.
2. You should see a table of WRF jobs in the system.
3. You can update the status with the following Python code.  You should immediately see changes in your web application after running the _update_job_in_system_ function.
```
import time
from wrfcloud.system import init_environment
from wrfcloud.jobs import get_all_jobs_in_system, update_job_in_system, WrfJob
init_environment('development')
jobs = get_all_jobs_in_system()
job1 = jobs[0]
job1.status_message = 'Pending'
job1.status_code = WrfJob.STATUS_CODE_PENDING
job1.progress = 0
update_job_in_system(job1, True)
job1.status_message = 'Initializing Cluster'
job1.status_code = WrfJob.STATUS_CODE_STARTING
job1.progress = 0
update_job_in_system(job1, …
```

Feature 61/wrf jobs in UI

---

python/src/wrfcloud/runtime/__init__.py
python/src/wrfcloud/runtime/metgrid.py
python/src/wrfcloud/runtime/run.py
python/src/wrfcloud/runtime/test.yml
python/src/wrfcloud/runtime/tools/check_wd_exist.py
python/src/wrfcloud/runtime/tools/make_wps_namelist.py
python/src/wrfcloud/runtime/ungrib.py

This PR introduces a number of QOL improvements in error checking, runtime control, and test.yaml defaults
- Updates to test.yaml
- Change default values to be more reasonable for AWS cluster testing
- Add new option "exists" that can specify different options for dealing with existing working directories for each task
- "die" (default): previous behavior, script will die with an exception
- "skip": skip the task for which there is an existing working directory
- "remove": remove the working directory and create a fresh one
- Allow local_data to be fully removed rather than needing to specify it as an empty string to pull remote data
- Automatically create top-level workdir (this was previous behavior, got changed accidentally)
- Save full config dictionary to runinfo; this is useful for …

A number of QOL improvements in preparation for real and WRF tasks

---

python/src/wrfcloud/runtime/__init__.py
python/src/wrfcloud/runtime/configurations/test/namelist.input
python/src/wrfcloud/runtime/metgrid.py
python/src/wrfcloud/runtime/real.py
python/src/wrfcloud/runtime/tools/__init__.py
python/src/wrfcloud/runtime/tools/check_wd_exist.py
python/src/wrfcloud/runtime/tools/make_wps_namelist.py
python/src/wrfcloud/runtime/tools/make_wrf_namelist.py
python/src/wrfcloud/runtime/wrf.py

This PR adds initial, head-node serial-only capabilities to run real.exe and WRF tasks.

Add real.exe and WRF capabilities

---

python/src/wrfcloud/runtime/__init__.py
python/src/wrfcloud/runtime/real.py
python/src/wrfcloud/runtime/test.yml
python/src/wrfcloud/runtime/tools/make_wrf_namelist.py
python/src/wrfcloud/runtime/wrf.py

This PR adds the "wrfcores" config option. If set to 1 (default), the previous serial-run behavior is maintained. If >1, the real.exe and WRF tasks will be submitted as a parallel job to the slurm queue with `wrfcores` number of cores. If >96, will fail with an error message, as the current default instance only has 96 cores available.
Resolves #74 
Ran tests with 1, 36, and 96 cores. 1 core defaulted to original (serial) behavior as expected (fails at real.exe due to lack of memory). 36 and 96 core tests worked as anticipated, with 96 cores running at ~20x realtime (0.9 wallclock seconds per 20s simulated time step). Attempted to run with 100 cores, and received the appropriate error message.
```
wrfcloud-cluster create
wrfcloud-cluster connect
git clone …
```

Add logic for parallel job submission through slurm

---

python/src/setup.py
python/src/wrfcloud/aws/resources/cf_imagebuilder_wrf_intel.yaml
python/src/wrfcloud/runtime/resources/geojson_products.yaml
python/src/wrfcloud/runtime/tools/geojson.py
python/src/wrfcloud/setup/aws/cf_wrfcloud_webapp.yaml

Feature 37/grib2 to geojson

---

python/src/wrfcloud/api/actions/login.py

Extended the JWT valid time.

---

LICENSE.md

This PR adds the Apache v2.0 license to WRF Cloud. Per discussion with UCAR Legal and development team, this is the best licensing choice. 
Closes #116.
No testing needed.
N/A
The license file is standard and auto-detectable by GitHub. 
N/A

Feature/116 Add a license

---

python/src/wrfcloud/api/actions/__init__.py
python/src/wrfcloud/api/actions/resources/run_wrf_template.sh
python/src/wrfcloud/api/actions/roles.yaml
python/src/wrfcloud/api/actions/wrf.py
python/src/wrfcloud/api/auth/__init__.py
python/src/wrfcloud/runtime/run.py

Added a new API Action to delete a cluster.
Cluster uses the JWT to call the API to shutdown when it is finished, rather than trying to delete its own stack.

Passed a JWT with to a cluster with a 'cluster' role.

---

web/src/app/wrf-viewer/wrf-viewer.component.html
web/src/app/wrf-viewer/wrf-viewer.component.sass
web/src/app/wrf-viewer/wrf-viewer.component.ts

The WRF output viewer map has a political boundaries layer.
All WRF jobs should have the new data layer.
Closes #143

Added a top layer to the map that contains political boundaries.

---

install_bootstrap.sh

The install script should use the version of nodejs 16.x that it installed rather than hard-coded to 16.19.0.
George will try to re-install the full system with this branch.  Delete the cloudshell home directory before starting the next install to ensure it is starting from a clean environment.
Closes #167

Resolve the NodeJS version dynamically, but we still want to use major version 16

---

web/src/app/wrf-viewer/wrf-viewer.component.html
web/src/app/wrf-viewer/wrf-viewer.component.sass
web/src/app/wrf-viewer/wrf-viewer.component.ts

The purpose of the height/pressure level selector should be more clear to the user.
The code is deployed to the website.  Test it on a variety of devices and browser window sizes.
Closes #46

46-height-selector

---

web/src/app/wrf-viewer/wrf-viewer.component.ts

Fixes the bug described in this issue.  Note: This issue's "Steps to reproduce" do not make sense.  This bug only applied to the 3D variables.
Change is deployed and can be tested from the website.

161-apply-transparency-to-3d

---

README.md

Feature 184 - Update UG link to stable version

---

docs/Users_Guide/administration.rst
python/src/wrfcloud/api/actions/__init__.py
python/src/wrfcloud/api/actions/action.py
python/src/wrfcloud/api/actions/logs.py
python/src/wrfcloud/api/actions/resources/run_wrf_template.sh
python/src/wrfcloud/api/actions/roles.yaml
python/src/wrfcloud/api/actions/wrf.py
python/src/wrfcloud/config/config.py
python/src/wrfcloud/jobs/job.py
python/src/wrfcloud/runtime/run.py
web/src/app/app.module.ts
web/src/app/client-api.ts
web/src/app/job-details/job-details.component.html
web/src/app/job-details/job-details.component.sass
web/src/app/job-details/job-details.component.ts
web/src/app/log-viewer/log-viewer.component.html
web/src/app/log-viewer/log-viewer.component.sass
web/src/app/log-viewer/log-viewer.component.spec.ts
web/src/app/log-viewer/log-viewer.component.ts

Started angular and viewed changes
Start angular to view changes from this branch and view job W83C165E19E logs. Note wrfcloud run log file is incomplete because I was testing

Feature #198 log viewer

---

python/src/wrfcloud/runtime/resources/geojson_products.yaml

These changes will change the color palette used for contouring the precipitation accumulation plot. The changes are just in visual appearance and should not change the underlying data. 
These changes close #214 
No testing has been done. I'm unsure how to deploy and view these changes. 
If possible to deploy these changes to simply view with existing runs, that should be sufficient. Otherwise launch a simple quick run to visually inspect the precip accumulation field to ensure it's using the new color palette.
None needed.
None needed. 
Select: **Development** to …

Feature 214 change precip accum colorbar
